# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events/compliance/document_assigned_to_student.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "learn_ipc.events.compliance.DocumentAssignedToStudent" do
    optional :user_uuid, :string, 1
    optional :correlation_id, :string, 2
    optional :uuid, :string, 3
    map :context, :string, :string, 4
    optional :data, :message, 5, "learn_ipc.events.compliance.DocumentAssignedToStudent.Data"
    optional :occurred_at, :string, 6
  end
  add_message "learn_ipc.events.compliance.DocumentAssignedToStudent.Data" do
    optional :student_uuid, :string, 1
    optional :kind, :string, 2
    optional :document_uuid, :string, 3
    optional :docusign_reference_id, :string, 4
  end
end

module LearnIpc
  module Events
    module Compliance
      DocumentAssignedToStudent = Google::Protobuf::DescriptorPool.generated_pool.lookup("learn_ipc.events.compliance.DocumentAssignedToStudent").msgclass
      DocumentAssignedToStudent::Data = Google::Protobuf::DescriptorPool.generated_pool.lookup("learn_ipc.events.compliance.DocumentAssignedToStudent.Data").msgclass
    end
  end
end
