# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events/student/registered.proto

require 'google/protobuf'

require_relative 'student_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "learn_ipc.events.student.Registered" do
    optional :user_uuid, :string, 1
    optional :correlation_id, :string, 2
    optional :uuid, :string, 3
    map :context, :string, :string, 4
    optional :data, :message, 5, "learn_ipc.entities.Student"
  end
end

module LearnIpc
  module Events
    module Student
      Registered = Google::Protobuf::DescriptorPool.generated_pool.lookup("learn_ipc.events.student.Registered").msgclass
    end
  end
end
