# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: entities/student.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "learn_ipc.entities.Student" do
    optional :learn_uuid, :string, 1
    optional :first_name, :string, 2
    optional :last_name, :string, 3
    optional :email, :string, 4
    optional :username, :string, 5
    optional :phone_number, :string, 6
    optional :external_id, :string, 7
  end
end

module LearnIpc
  module Entities
    Student = Google::Protobuf::DescriptorPool.generated_pool.lookup("learn_ipc.entities.Student").msgclass
  end
end
