# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: commands/create_batch.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "learn_ipc.commands.TestMessage" do
    optional :user_uuid, :string, 1
    optional :correlation_id, :string, 2
    optional :uuid, :string, 3
    optional :type, :string, 4
    optional :data, :message, 5, "learn_ipc.commands.TestMessage.Data"
  end
  add_message "learn_ipc.commands.TestMessage.Data" do
    optional :iteration, :string, 1
  end
end

module LearnIpc
  module Commands
    TestMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("learn_ipc.commands.TestMessage").msgclass
    TestMessage::Data = Google::Protobuf::DescriptorPool.generated_pool.lookup("learn_ipc.commands.TestMessage.Data").msgclass
  end
end
