# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: commands/create_batch.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "learn_ipc.commands.UnhandledMessage" do
    optional :user_uuid, :int32, 1
    optional :correlation_id, :int32, 2
    optional :uuid, :string, 3
    optional :type, :string, 4
    optional :data, :message, 5, "learn_ipc.commands.UnhandledMessage.Data"
  end
  add_message "learn_ipc.commands.UnhandledMessage.Data" do
    optional :iteration, :string, 1
  end
end

module LearnIpc
  module Commands
    UnhandledMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("learn_ipc.commands.UnhandledMessage").msgclass
    UnhandledMessage::Data = Google::Protobuf::DescriptorPool.generated_pool.lookup("learn_ipc.commands.UnhandledMessage.Data").msgclass
  end
end
