# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lib/src/events/base_message.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "railway_ipc.BaseMessage" do
    optional :user_uuid, :string, 1
    optional :correlation_id, :string, 2
    optional :uuid, :string, 3
    map :context, :string, :string, 4
    optional :data, :message, 5, "railway_ipc.BaseMessage.Data"
  end
  add_message "railway_ipc.BaseMessage.Data" do
  end
end

module RailwayIpc
  BaseMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("railway_ipc.BaseMessage").msgclass
  BaseMessage::Data = Google::Protobuf::DescriptorPool.generated_pool.lookup("railway_ipc.BaseMessage.Data").msgclass
end
